{% set name = "cy-py-test" %}
{% set version = "0.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path:  ./

requirements:
  build:
    - python =3.11
    - pip
    - numpy >=2.0
    - cython
    - setuptools
    - wheel
  host:
    - python =3.11
    - pip
    - numpy >=2.0
    - cython
    - setuptools
    - wheel
  run:
    - python =3.11
    - numpy >=2.0
    - cython

about:
  home: https://test.pypi.org/project/cy-py-test/
  summary: "A test package for conda build experiments"
  license: MIT
  license_family: MIT

