{% set name = "cy-py-test" %}
{% set version = "0.2.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/sergey-yaroslavtsev/cy_py_release_testing/archive/refs/tags/v{{ version }}.tar.gz
  sha256: <fill-in-sha256>

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://test.pypi.org/project/cy-py-test/
  summary: "A test package for conda build experiments"
  license: MIT
  license_family: MIT

