name: Build Conda Package

on:
  workflow_dispatch:  # manual trigger

jobs:
  build-conda-package:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true

      - name: Install conda-build
        run: conda install -c conda-forge conda-build -y

      - name: Build conda package
        run: |
         cd conda 
         conda build . --output-folder ./conda-bld

      - name: Upload conda package artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-conda-package
          path: conda-bld/*.tar.bz2
