name: Build Conda Package

on:
  workflow_dispatch:  # manual trigger

jobs:
  build-conda-package:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Miniforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          python-version: 3.11
          auto-update-conda: true

      - name: Install conda-build
        run: conda install -c conda-forge conda-build -y

      - name: Build conda package
        run: |
         cd conda 
         conda build . --output-folder ./conda-bld

      - name: List conda build output
        run: |
          ls -R 
          ls -R conda
          ls -R conda/conda-bld
          ls -R conda/conda-bld/osx-64

      - name: Upload conda package artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda-package
          path: conda-bld/**/*.{tar.bz2,conda}
        working-directory: conda
