name: Release to TestPyPI

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-latest, windows-latest]
          python-version: ["3.11", "3.12"]
    steps:
      - name: Determine cibw-version
        id: cibw
        run: |
          case "${{ matrix.python-version }}" in
            "3.11") echo "cibw_version=311" ;;
            "3.12") echo "cibw_version=312" ;;
            *) echo "cibw_version=unknown" ;;
          esac >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel and tools
        run: |
          python -m pip install --upgrade cibuildwheel twine

      - name: Install build dependencies
        run: python -m pip install --upgrade setuptools wheel numpy cython

      - name: Build wheels with cibuildwheel for Python ${{ matrix.python-version }}
        env:
          CIBW_BUILD: cp${{ steps.cibw.outputs.cibw_version }}-*
          CIBW_OUTPUT_DIR: wheelhouse
          CIBW_BUILD_FRONTEND: build
          CIBW_BUILD_VERBOSITY: 1
        run: |
          python -m cibuildwheel --output-dir wheelhouse #--debug-traceback

      - name: Upload wheels to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
        run: |
          python -m twine upload --repository testpypi wheelhouse/*.whl
        # python -m twine upload --repository testpypi wheelhouse/*.whl --verbose
