name: Release to TestPyPI

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12 to run cibuildwheel
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install build tools
        run: |
          python -m pip install --upgrade cibuildwheel twine build

      - name: Build wheels with cibuildwheel for Python 3.12
        env:
          CIBW_BUILD: cp312-*
          CIBW_OUTPUT_DIR: wheelhouse
          CIBW_BUILD_FRONTEND: build
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
        run: python -m twine upload --repository testpypi wheelhouse/*.whl