name: Release to TestPyPI

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: 3.9
            python-version-no-dot: 39
          - python-version: 3.10
            python-version-no-dot: 310
          - python-version: 3.11
            python-version-no-dot: 311
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel and tools
        run: |
          python -m pip install --upgrade cibuildwheel twine

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD: cp${{ matrix.python-version-no-dot }}-*
          CIBW_SKIP: cp27-*
          CIBW_OUTPUT_DIR: wheelhouse
          CIBW_BUILD_FRONTEND: build
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_TOKEN }}
        run: |
          python -m twine upload --repository testpypi wheelhouse/*.whl
